ADMIN BOOKS

<hr>

<table class="table table-striped books-list-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <?php foreach ($books as $book) : ?>
          <tr>
            <td><?=$book->getId() ?></td>
            <td><?=$book->getTitle() ?></td>
            <td><?=$book->getPrice() ?></td>
            <td>
                <a href="/admin/book/edit/<?=$book->getId()?>" class="btn btn-success btn-sm" aria-label="Left Align">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="#" class="btn btn-danger btn-sm" aria-label="Left Align">
                  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </td>
          </tr>
        <?php endforeach ?>
    </tbody>
</table>