<h1>Books</h1>

<hr>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :?> 
        <li <?=$button->isActive ? '' : 'class="disabled"' ?> >
            <?php if ($button->isActive) : ?>
                <a href="/index.php?route=book/index&amp;page=<?=$button->page?>"><?=$button->text?></a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>  
  </ul>
</nav>

<div class="row" id='js-books'>
    <div class="col-sm-6 col-md-4" style='display:none' id='js-book-item-tpl'>
      <div class="thumbnail book-item">
        <img src="https://i.ytimg.com/vi/prALrHUJ8Ns/hqdefault.jpg" alt="">
        <div class="caption">
          <h3></h3>
          <p></p>
          <p>
              <a href="#" class="btn btn-primary" role="button">Details</a> 
              <a href="/cart/add/" class="btn btn-default js-add-to-cart" role="button" data-id=''>Add to cart</a>
          </p>
        </div>
      </div>
    </div>
  
    
    <?php foreach ($books as $book) : ?>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail book-item">
          <img src="https://i.ytimg.com/vi/prALrHUJ8Ns/hqdefault.jpg" alt="">
          <div class="caption">
            <h3><?=$book->getTitle();?></h3>
            <p><?=$book->getDescription();?></p>
            <p>
                <a href="#" class="btn btn-primary" role="button">Details</a> 
                <a href="/cart/add/<?=$book->getId();?>" class="btn btn-default js-add-to-cart" role="button" data-id='<?=$book->getId();?>'>Add to cart</a>
            </p>
          </div>
        </div>
      </div>
    <?php endforeach ?>
    
</div>

<button type='button' class='btn btn-lg btn-primary' id='js-load-books' data-offset='10' data-count='10'>Load more books</button>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :?> 
        <li <?=$button->isActive ? '' : 'class="disabled"' ?> >
            <?php if ($button->isActive) : ?>
                <a href="/index.php?route=book/index&amp;page=<?=$button->page?>"><?=$button->text?></a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>  
  </ul>
</nav>


<script>
  $(document).ready(function() {
      $(document).on('click', '.js-add-to-cart',function(e) {
        e.preventDefault();
        var id = $(this).data('id');
        $.get('/api/cart/add/' + id, function() {
          alert('Book ' + id + ' added');
        });
      });
    
      var $loadBtn = $('#js-load-books');
      var url = '/api/books?count=' + $loadBtn.data('count') + '&offset=';
    
      // handlers for handling different response status codes
      function handleSuccess(response) {
          var books = response.data;
          var key;
          var $bookItemTpl = $('#js-book-item-tpl'); 
          var $books = $('#js-books');
          var $caption, $link, linkHref;
          
          for (key in books) {
            var book = books[key];
            var $bookItem =  $bookItemTpl.clone();
            $caption = $bookItem.find('div.caption')
            $caption.find('h3').first().text(book.title);
            $caption.find('p').first().text(book.description);
            $link = $caption.find('a').last();
            linkHref = $link.attr('href');
            $link.attr('href', linkHref + book.id);
            $link.data('id', book.id);
            
            $bookItem.fadeIn();
            $books.append($bookItem);
          }
          
          var offset = parseInt($loadBtn.data('offset'));
          offset += parseInt($loadBtn.data('count'));
          $loadBtn.data('offset', offset);
          
          console.log('success', response);
      }
      
      function handleFail(res) {
          // todo
          // var msg = JSON.parse(res.responseText);
          // $messageBox.html('<b>Save failed! ' + msg.data + '</b>');
          console.log('fail');
      }
     
      $loadBtn.click(function() {
        var offset = $loadBtn.data('offset');
        
        $.ajax({
          type: 'GET',
          url: url + offset , // todo: how to not hardcode URL?
          statusCode: {
              200: handleSuccess,
              404: handleFail,
              500: handleFail
          }
        }).always(function() {
            // $spinner.hide();
            console.log('always');
        });
    });
 });
  
</script>