<h1>Books</h1>

<hr>

<nav aria-label="Page navigation">
  <ul class="pagination">
    <?php foreach ($pagination->buttons as $button) :?> 
        <li <?=$button->isActive ? '' : 'class="disabled"' ?> >
            <?php if ($button->isActive) : ?>
                <a href="/index.php?route=book/index&amp;page=<?=$button->page?>"><?=$button->text?></a>
            <?php else : ?>
                <span aria-hidden="true"><?=$button->text?></span>
            <?php endif ?>
        </li>
    <?php endforeach ?>  
  </ul>
</nav>

<div class="row">

	<?php foreach ($books as $book) : ?> 
	  <div class="col-sm-6 col-md-4">
	    <div class="thumbnail book-item">
	      <img src="/img/book.gif" alt="">
	      <div class="caption">
	        <h3><?=$book->getTitle();?></h3>
	        <p><?=$book->getDescription();?></p>
	        <p>
	        <a href="#" class="btn btn-primary" role="button">Details</a>
	        <a href="#" class="btn btn-default" role="button">Add to catr</a>
	        </p>
	      </div>
	    </div>
	  </div>
	<?php endforeach ?>

</div>
